openapi: 3.0.3
info:
  title: Swagger - OpenAPI 3.0
  description: Создание и получение снепшота корзины
  version: 1.0.0
servers:
  - url: https://5ka.ru.swagger.io/api/v1
tags:
  - name: snapshotbasket
    description: методы для работы с корзинами товаров, создание снимка корзины
  - name: snapshotid
    description: методы для получения снимка корзины

paths:
  /basketsnapshot/:
    post:
      tags:
        - snapshotbasket
      summary: создание снимка корзины
      description: создание снимка корзины, содержащего список товаров
      requestBody:
        description: параметры метода для создания снимка корзины
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasketSnapshot'
      responses:
       '200':
         description: успешное создание снепшота корзины
         content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasketsnapshotIdResponse'
      
  /basketsnapshot/{basketSnapshotId}:
    get:
      tags:
        - snapshotid
      summary: получить снимок корзины по идентификатору
      description: получить снимок корзины по идентификатору
      parameters:
        - name: basketSnapshotId
          in: path
          description: id снепшота
          required: true
          schema:
            type: integer
            example: 11
      responses:
       '200':
         description: Success
         content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasketSnapshotResponse' 




                

components:
  schemas:
    BasketSnapshot:
      type: object
      properties:
        basketItems:
          type: array
          items:
           type: object
           properties:
              productId:
                type: integer
                description: Уникальный ID Товара
                example: 1
              name:
                type: string
                description: Наименование Товара
                example: Milk
              price:
                type: number
                description: Цена за единицу Товара
                example: 79.99
              quantity:
                type: integer
                description: Количество Товара
                example: 2
      required:
        - basketItems

 
    BasketsnapshotIdResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: код ответа
        message:
          type: string
          description: сообщение об успешном выполнении операции
          example: 'id снепшота создан'
        basketSnapshotId:
          type: integer
          description: id снепшота
          example: 456
      required:
              - message
              - basketSnapshotId

    BasketSnapshotResponse:
      type: object
      properties:
        creationDate:
          type: string
          format: date-time
          example: 2024-12-20T09:12Z
        basketItems:
          type: array
          items:
           type: object
           properties:
             productId:
              type: integer
              example: 12
             name:
              type: string
              example: Milk
             price:
              type: number
              example: 79.99
             quantity:
              type: integer
              example: 2
           required:
              - productId
              - name
              - price
              - quantity
      required:
            - creationDate
      

     
     

     
